In [3]:
# Importando Bibliotecas
import pandas as pd

In [4]:
df = pd.read_csv('tabela-de-oficinas.csv', encoding='utf-8', sep="\t", header=None)

df.columns = ['Nome', 'Protocolo', 'Mes', 'Resultado']

In [5]:
df_sem_nome_e_mes = df.drop(['Nome', 'Mes'], axis=1,inplace=False)

In [6]:
df_sem_nome_e_mes

            Protocolo        Resultado
0   00012024069895T01      RECOMENDADO
1   00012024070428S00  NÃO RECOMENDADO
2   00012024070428T02      RECOMENDADO
3   00012024070480T01      RECOMENDADO
4   00012024070579T01  NÃO RECOMENDADO
..                ...              ...
62  00522024075726T01      RECOMENDADO
63  00522024075989S00      RECOMENDADO
64  00522024076777S00      RECOMENDADO
65  00522024076807S00  NÃO RECOMENDADO
66  00522024077215T01      RECOMENDADO

[67 rows x 2 columns]

In [7]:

df_recomendado = df_sem_nome_e_mes[df_sem_nome_e_mes['Resultado'] == 'RECOMENDADO']
print(df_recomendado)

            Protocolo    Resultado
0   00012024069895T01  RECOMENDADO
2   00012024070428T02  RECOMENDADO
3   00012024070480T01  RECOMENDADO
5   00012024070704T01  RECOMENDADO
6   00012024070758T01  RECOMENDADO
9   00012024071010T01  RECOMENDADO
10  00012024071035T01  RECOMENDADO
13  00012024071413S00  RECOMENDADO
14  00012024071427T01  RECOMENDADO
15  00012024071780T01  RECOMENDADO
16  00012024072124T01  RECOMENDADO
17  00012024072265S00  RECOMENDADO
18  00012024072265T01  RECOMENDADO
19  00012024072326T01  RECOMENDADO
21  00012024072830T01  RECOMENDADO
24  00012024073360S00  RECOMENDADO
25  00012024073389T01  RECOMENDADO
27  00012024073451S00  RECOMENDADO
30  00012024073505T01  RECOMENDADO
31  00012024073518T01  RECOMENDADO
34  00012024075194T01  RECOMENDADO
35  00012024075478T01  RECOMENDADO
39  00012024076816S00  RECOMENDADO
40  00012024077064T01  RECOMENDADO
41  00012024077251S00  RECOMENDADO
42  00012024077402S00  RECOMENDADO
43  00012024077402T01  RECOMENDADO
44  00012024077458S00  RECOMENDADO
45  00012024077458T01  RECOMENDADO
47  00522024070532T01  RECOMENDADO
48  00522024070552T01  RECOMENDADO
49  00522024071324T01  RECOMENDADO
50  00522024071600S00  RECOMENDADO
51  00522024071815T05  RECOMENDADO
52  00522024072073T01  RECOMENDADO
53  00522024072119S00  RECOMENDADO
54  00522024072372T01  RECOMENDADO
55  00522024072580T01  RECOMENDADO
56  00522024073275S00  RECOMENDADO
62  00522024075726T01  RECOMENDADO
63  00522024075989S00  RECOMENDADO
64  00522024076777S00  RECOMENDADO
66  00522024077215T01  RECOMENDADO

In [8]:
df_recomendado

            Protocolo    Resultado
0   00012024069895T01  RECOMENDADO
2   00012024070428T02  RECOMENDADO
3   00012024070480T01  RECOMENDADO
5   00012024070704T01  RECOMENDADO
6   00012024070758T01  RECOMENDADO
9   00012024071010T01  RECOMENDADO
10  00012024071035T01  RECOMENDADO
13  00012024071413S00  RECOMENDADO
14  00012024071427T01  RECOMENDADO
15  00012024071780T01  RECOMENDADO
16  00012024072124T01  RECOMENDADO
17  00012024072265S00  RECOMENDADO
18  00012024072265T01  RECOMENDADO
19  00012024072326T01  RECOMENDADO
21  00012024072830T01  RECOMENDADO
24  00012024073360S00  RECOMENDADO
25  00012024073389T01  RECOMENDADO
27  00012024073451S00  RECOMENDADO
30  00012024073505T01  RECOMENDADO
31  00012024073518T01  RECOMENDADO
34  00012024075194T01  RECOMENDADO
35  00012024075478T01  RECOMENDADO
39  00012024076816S00  RECOMENDADO
40  00012024077064T01  RECOMENDADO
41  00012024077251S00  RECOMENDADO
42  00012024077402S00  RECOMENDADO
43  00012024077402T01  RECOMENDADO
44  00012024077458S00  RECOMENDADO
45  00012024077458T01  RECOMENDADO
47  00522024070532T01  RECOMENDADO
48  00522024070552T01  RECOMENDADO
49  00522024071324T01  RECOMENDADO
50  00522024071600S00  RECOMENDADO
51  00522024071815T05  RECOMENDADO
52  00522024072073T01  RECOMENDADO
53  00522024072119S00  RECOMENDADO
54  00522024072372T01  RECOMENDADO
55  00522024072580T01  RECOMENDADO
56  00522024073275S00  RECOMENDADO
62  00522024075726T01  RECOMENDADO
63  00522024075989S00  RECOMENDADO
64  00522024076777S00  RECOMENDADO
66  00522024077215T01  RECOMENDADO

In [9]:
df_nao_recomendado = df_sem_nome_e_mes[df_sem_nome_e_mes['Resultado'] == 'NÃO RECOMENDADO']
print(df_nao_recomendado)

            Protocolo        Resultado
1   00012024070428S00  NÃO RECOMENDADO
4   00012024070579T01  NÃO RECOMENDADO
7   00012024070809T01  NÃO RECOMENDADO
8   00012024070981S00  NÃO RECOMENDADO
11  00012024071058T01  NÃO RECOMENDADO
12  00012024071237T01  NÃO RECOMENDADO
20  00012024072794S00  NÃO RECOMENDADO
22  00012024072846T01  NÃO RECOMENDADO
23  00012024073325T01  NÃO RECOMENDADO
26  00012024073451S00  NÃO RECOMENDADO
28  00012024073451T01  NÃO RECOMENDADO
29  00012024073470T01  NÃO RECOMENDADO
32  00012024074055S00  NÃO RECOMENDADO
33  00012024074262T01  NÃO RECOMENDADO
36  00012024075725T01  NÃO RECOMENDADO
37  00012024076019S00  NÃO RECOMENDADO
38  00012024076163T01  NÃO RECOMENDADO
46  00522024070087T01  NÃO RECOMENDADO
57  00522024073350T01  NÃO RECOMENDADO
58  00522024074010S00  NÃO RECOMENDADO
59  00522024074018T01  NÃO RECOMENDADO
60  00522024074380T01  NÃO RECOMENDADO
61  00522024075033T01  NÃO RECOMENDADO
65  00522024076807S00  NÃO RECOMENDADO

In [10]:
df_nao_recomendado

            Protocolo        Resultado
1   00012024070428S00  NÃO RECOMENDADO
4   00012024070579T01  NÃO RECOMENDADO
7   00012024070809T01  NÃO RECOMENDADO
8   00012024070981S00  NÃO RECOMENDADO
11  00012024071058T01  NÃO RECOMENDADO
12  00012024071237T01  NÃO RECOMENDADO
20  00012024072794S00  NÃO RECOMENDADO
22  00012024072846T01  NÃO RECOMENDADO
23  00012024073325T01  NÃO RECOMENDADO
26  00012024073451S00  NÃO RECOMENDADO
28  00012024073451T01  NÃO RECOMENDADO
29  00012024073470T01  NÃO RECOMENDADO
32  00012024074055S00  NÃO RECOMENDADO
33  00012024074262T01  NÃO RECOMENDADO
36  00012024075725T01  NÃO RECOMENDADO
37  00012024076019S00  NÃO RECOMENDADO
38  00012024076163T01  NÃO RECOMENDADO
46  00522024070087T01  NÃO RECOMENDADO
57  00522024073350T01  NÃO RECOMENDADO
58  00522024074010S00  NÃO RECOMENDADO
59  00522024074018T01  NÃO RECOMENDADO
60  00522024074380T01  NÃO RECOMENDADO
61  00522024075033T01  NÃO RECOMENDADO
65  00522024076807S00  NÃO RECOMENDADO

In [12]:
def total_de_protocolos(df):
    return df['Protocolo'].count()

def calculo_porcentagem_recomendado(df):
    return len(df_recomendado) / total_de_protocolos(df) * 100

def calculo_porcentagem_nao_recomendado(df):
    return len(df_nao_recomendado) / total_de_protocolos(df) * 100

def nova_tabela(df):
    return total_de_protocolos(df), calculo_porcentagem_recomendado(df), calculo_porcentagem_nao_recomendado(df)

nova_tabela(df)
pd.concat([df_sem_nome_e_mes, df_recomendado, df_nao_recomendado])

            Protocolo        Resultado
0   00012024069895T01      RECOMENDADO
1   00012024070428S00  NÃO RECOMENDADO
2   00012024070428T02      RECOMENDADO
3   00012024070480T01      RECOMENDADO
4   00012024070579T01  NÃO RECOMENDADO
..                ...              ...
58  00522024074010S00  NÃO RECOMENDADO
59  00522024074018T01  NÃO RECOMENDADO
60  00522024074380T01  NÃO RECOMENDADO
61  00522024075033T01  NÃO RECOMENDADO
65  00522024076807S00  NÃO RECOMENDADO

[134 rows x 2 columns]